"""SQLAlchemy ORM models."""

from datetime import datetime

from sqlalchemy import (
    JSON,
    Column,
    Date,
    DateTime,
    ForeignKey,
    Integer,
    String,
    UniqueConstraint,
)
from sqlalchemy.orm import relationship

from app.core.database.database import Base


class User(Base):
    """A registered player able to submit scores."""

    __tablename__ = "users"

    id = Column(Integer, primary_key=True, index=True)
    username = Column(String(50), unique=True, index=True, nullable=False)
    email = Column(String(255), unique=True, index=True, nullable=False)
    password_hash = Column(String(255), nullable=False)
    created_at = Column(DateTime, default=datetime.utcnow, nullable=False)

    scores = relationship(
        "Score",
        back_populates="user",
        cascade="all, delete-orphan",
    )


class Score(Base):
    """A single solved puzzle time for a given user and game type."""

    __tablename__ = "scores"

    id = Column(Integer, primary_key=True, index=True)
    user_id = Column(
        Integer,
        ForeignKey("users.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    game_type = Column(String(30), default="zip", nullable=False, index=True)
    completion_time = Column(Integer, nullable=False, index=True)  # seconds
    created_at = Column(DateTime, default=datetime.utcnow, nullable=False, index=True)

    user = relationship("User", back_populates="scores")


class DailyPuzzle(Base):
    """A generated puzzle for a specific game and UTC date.

    Rows are pre-generated by the buffer (see ``crud/puzzles.py``) so a stored
    puzzle is always available to fall back on if live generation fails.
    """

    __tablename__ = "daily_puzzles"

    id = Column(Integer, primary_key=True, index=True)
    game_type = Column(String(30), nullable=False, index=True)
    locale = Column(String(2), default="es", nullable=False, index=True)
    puzzle_date = Column(Date, nullable=False, index=True)
    seed = Column(Integer, nullable=False)
    payload = Column(JSON, nullable=False)  # board sent to the client
    solution = Column(JSON, nullable=True)  # reference solution (server-only)
    created_at = Column(DateTime, default=datetime.utcnow, nullable=False)

    __table_args__ = (
        UniqueConstraint(
            "game_type",
            "locale",
            "puzzle_date",
            name="uq_daily_puzzle_game_locale_date",
        ),
    )
